#!/bin/bash

PROGRAMS=(
    "alacritty"
    "firefox"
    "fuzzel"
    "git"
    "grimshot"
    "helix"
    "i3status-rust"
    "lshw"
    "neofetch"
    "playerctl"
    "python3"
    "stow"
    "sway"
    "wdisplays"
    "zoxide"
    "zsh"
)

REPOS=(
    "atim/i3status-rust"
)

install_programs() {
    echo "Installing programs..."
    sudo dnf copr enable -y "${REPOS[@]}"
    sudo dnf install -y "${PROGRAMS[@]}"
}

stow_dotfiles() {
    DIRNAME="$(dirname "$0")"    
    echo "Stowing dotfiles..."
    stow -t "$HOME" "$DIRNAME"
}

dl_omz() {
    if [ ! -d "$HOME/.oh-my-zsh" ]; then
        echo "Cloning OMZ..."
        git clone "https://github.com/ohmyzsh/ohmyzsh.git" "$HOME/.oh-my-zsh"
    fi
}

main() {
    install_programs
    stow_dotfiles
    dl_omz
    chsh -s /usr/bin/zsh
    $HOME/.bin/fetch_potd
    echo "Setup complete!"
    neofetch
}

# Execute main function
main
