[icons]
icons = "awesome6"

[[block]]
block = "pomodoro"

[[block]]
block = "net"
format = " $icon $ssid "

[[block]]
block = "net"
format = " ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "sound"
max_vol = 100
headphones_indicator = true

[[block]]
block = "battery"
format = " $icon $percentage "
empty_format = " $icon $percentage "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d.%m. %R') "


