#!/usr/bin/env python3

import sys
import random

def abs(x):
    if x < 0:
        return -x
    else:
        return x

def cleanhex(x):
    return format(int(x), '02x')

if len(sys.argv) > 1:
    random.seed(a=sys.argv[1]) # optionally use first argument as seed (eg. openssl-rand)

H = random.random()*360 # hue in degrees
S = random.random() # saturation 0-1
L = random.random() # saturation 0-1

C = (1 - abs(2*L - 1)) * S
X = C * (1 - abs((H/60) % 2 -1))
m = L - C/2

if     0 <= H and H <  60:
    R, G, B = C, X, 0
elif  60 <= H and H < 120:
    R, G, B = X, C, 0
elif 120 <= H and H < 180:
    R, G, B = 0, C, X
elif 180 <= H and H < 240:
    R, G, B = 0, X, C
elif 240 <= H and H < 300:
    R, G, B = X, 0, C
else: # elif 300 <= H and H < 360:
    R, G, B = C, 0, X

R = (R+m)*255
G = (G+m)*255
B = (B+m)*255

print("" + cleanhex(R) + cleanhex(G) + cleanhex(B))
