[[language]]
name = "latex"
language-servers = ["texlab"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
auto-format = true
indent = { tab-width = 4, unit = "t" }

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language-servers]]
name = "texlab"
config = { texlab = { build = { onSave = true, forwardSearchAfter = true }, forwardSearch = { executable = "zathura", args = [ "--synctex-forward", "%l:1:%f", "%p" ] }, chktex = { onEdit = true } } }

